create table if not exists public.products(
id bigint generated by default as identity primary key,name text not null,description text,price numeric(12,2) not null,old_price numeric(12,2),stock integer not null default 0,category text not null default 'General',image_url text,active boolean not null default true,created_at timestamptz default now());

create table if not exists public.orders(
id bigint generated by default as identity primary key,customer_name text not null,phone text not null,address text not null,city text,total numeric(12,2) not null,payment_method text not null,payment_status text default 'pending',order_status text default 'pending',transaction_id text,created_at timestamptz default now());

create table if not exists public.order_items(
id bigint generated by default as identity primary key,order_id bigint references public.orders(id) on delete cascade,product_id bigint,product_name text not null,price numeric(12,2) not null,quantity integer not null,size text,color text);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "public read active products" on public.products for select using(active=true);
create policy "public create orders" on public.orders for insert with check(true);
create policy "public create order items" on public.order_items for insert with check(true);

insert into public.products(name,price,old_price,stock,category,image_url) values
('Premium Oversized T-Shirt',899,1199,20,'Men','https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=900'),
('Classic Casual Shirt',1299,1699,14,'Men','https://images.unsplash.com/photo-1603252110481-7ba873bf42ab?w=900'),
('Women Oversized Tee',949,1299,16,'Women','https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=900');